### Governance Dataset:
The governance dataset has information about not-for-profits such as the number of voting memters and volunteers.  Additionally, it includes a number of boolean datatype fields related to policies or disclosures such as a conflict of interest policy or a conflict disclosure.  The evidence of robust policies and disclosure practices are indicators of organizations with strong internal controls.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
# examine all fields
df_all_fields = pd.read_csv('data_sets/Open990_Governance_Snack_Set_Public_2019-01-15.csv', nrows=5)

In [3]:
df_all_fields.head()

,ein,name_org,tax_date_begin,tax_date_end,tax_yr,doing_business_as,phone,website,address,city,state,country,zip,org_form.association,org_form.corp,org_form.other_form,org_form.other_form_desc,org_form.trust,formation_yr,grp_exempt_num,state_legaldomicile,grp_return,grp_subs_all_incl,exempt_status.501c3,exempt_status.501c_any,exempt_status.501c_txt,gross_receipts,ntee_code_nccs,ntee_description_nccs,discontinue_dispose25,voting_memb_ct,voting_indepmemb_ct,employee_tot_ct,volunteer_tot_ct,income_tot_unrelated,income_net_unrelated,rev_giftsgrants_tot_prioryr,rev_prgmservice_prioryr,rev_investmt_prioryr,rev_other_prioryr,rev_tot_prioryr,grants_expense_tot_prioryr,benefits_expense_tot_prioryr,salaries_expense_tot_prioryr,fundraiseservfee_expense_tot_prioryr,fundraise_expense_tot_curyr,other_expense_tot_prioryr,expense_tot_prioryr,rev_less_expense_prioryr,asset_tot_beginyr,liability_tot_beginyr,asset_net_beginyr,rev_giftsgrants_tot_curyr,rev_prgmservice_curyr,rev_investmt_curyr,rev_other_curyr,rev_tot_curyr,grants_expense_tot_curyr,benefits_expense_tot_curyr,salaries_expense_tot_curyr,fundraiseservfee_expense_tot_curyr,other_expense_tot_curyr,expense_tot_curyr,rev_less_expense_curyr,asset_tot_endyr,liability_tot_endyr,asset_net_endyr,operate_hospfacility,relationsamongemployees,delegate_management,material_diversion,memb_or_stockholder,memb_elect_board,decisions_outside_board,govern_body_minutes,committee_minutes,no_officer_address,local_chapt,policies_ref_chapt,990_to_members,conflict_interest_policy,conflict_disclosure,enforce_conflict_policy,whistleblower_policy,doc_retention_policy,ceo_comp_review,officer_comp_review,in_joint_venture,joint_venture_policy,forms_ownwebsite,comp_currkeypersons_tot,cash_noninterest_endyr,savingtempcash_endyr,pledges_net_endyr,accountreceivable_net_endyr,invest_publicsec_endyr,invest_othersec_endyr,invest_prog_endyr,asset_intangible_endyr,asset_unrestrictnet_endyr,asset_temprestrictnet_endyr,asset_permrestrictnet_endyr,record_id,schema_version,irs_efile_id,random_string
0,391546606,DAYSTAR INC,2017-01-01,2017-12-31,2017,NaN,+1 (414) 385-0334,WWW.DAYSTARINC.ORG,PO BOX 2130,MILWAUKEE,WI,NaN,532012130,NaN,True,NaN,NaN,NaN,1986,NaN,WI,no,NaN,True,NaN,NaN,333897,NaN,NaN,NaN,9,9,8,25.0,4280,0.0,207987,6092,1,-143,213937,0.0,0.0,140200,0.0,21971,92928,233128,-19191,316735,288974,27761,260639,8695,0,4280,273614,0,0,115568,0,115084,230652,42962,325654,254931,70723,no,no,no,no,no,no,no,yes,yes,no,no,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,NaN,NaN,16375.0,27988,201.0,17998.0,6009.0,NaN,NaN,NaN,NaN,70723.0,0.0,NaN,391546606_201712,2017v2.2,201831219349300733,MTA0MDA1NjUyMDM1ODQ2NDI1MQ
1,640901077,HERNANDO MAIN STREETCHAMBER OF COMMERCE,2012-01-01,2012-12-31,2012,NaN,+1 (662) 429-9055,www.hernandoms.org,2440 HIGHWAY 51 SOUTH,HERNANDO,MS,NaN,38632,NaN,True,NaN,NaN,NaN,1973,NaN,MS,no,no,NaN,True,6.0,252283,S41,Promotion of Business,NaN,15,15,4,NaN,0,NaN,92322,4740,649,18732,116443,NaN,NaN,87063,NaN,-103606,81181,168244,-51801,89517,7271,82246,81249,40715,296,26417,148677,965,0,83768,0,76994,161727,-13050,72742,3546,69196,no,no,no,no,yes,yes,yes,yes,no,no,no,NaN,yes,yes,yes,yes,no,no,no,no,no,NaN,NaN,45010.0,30403,34216.0,0.0,6738.0,0.0,0.0,0.0,0.0,69196.0,NaN,NaN,640901077_201212,2012v2.0,201321359349303692,MTA0MDA1NzYwNzM0ODkyMTY0Ng
2,522113016,MARYLAND CAPITAL ENTERPRISES INC,2014-10-01,2015-09-30,2015,NaN,+1 (410) 546-1900,WWW.MARYLANDCAPITAL.ORG,PO BOX 213,SALISBURY,MD,NaN,21802,NaN,True,NaN,NaN,NaN,1991,NaN,MD,no,NaN,True,NaN,NaN,1406736,P51,"Financial Counseling, Money Management",NaN,15,15,16,0.0,0,0.0,1324919,0,170539,59726,1555184,0.0,0.0,337154,0.0,0,589747,926901,628283,4376943,2518702,1858241,1091077,0,257136,51865,1400078,0,0,517577,0,386300,903877,496201,5435095,3080653,2354442,no,no,no,no,no,no,no,yes,yes,no,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,no,NaN,NaN,28139.0,486696,802607.0,119721.0,NaN,NaN,NaN,NaN,NaN,1915868.0,NaN,438574.0,522113016_201509,2014v6.0,201622259349303247,MTA0MDA1NzYyMjEwNzcwOTk1Ng
3,454957549,OLD SCHOOL LIVES INCORPORATED,2016-01-01,2016-12-31,2016,NaN,+1 (218) 482-3005,NaN,PO BOX 156,COTTON,MN,NaN,55724,NaN,True,NaN,NaN,NaN,2012,NaN,MN,no,no,True,NaN,NaN,249597,NaN,NaN,NaN,4,0,12,NaN,0,NaN,80265,10229,563,48575,139632,2300.0,NaN,37749,NaN,15,94602,134651,4981,86320,19044,67276,93785,11660,1031,117498,223974,1141,0,79260,0,153716,234117,-10143,92651,35518,57133,no,no,no,no,no,no,no,no,no,no,no,NaN,no,no,no,no,no,no,no,no,no,NaN,NaN,14400.0,11626,5756.0,0.0,6711.0,0.0,0.0,0.0,0.0,48197.0,8936.0,NaN,454957549_201612,2016v3.0,201723189349310957,MTA0MDA5MjM3MzQ3MTE4MDEyNw
4,210502065,GREATER LONG BRANCH CHAMBER OF COMMERCE,2017-01-01,2017-12-31,2017,NaN,+1 (732) 222-0400,WWW.LONGBRANCHCHAMBER.ORG,PO BOX 628,LONG BRANCH,NJ,NaN,7740,NaN,True,NaN,NaN,NaN,1935,NaN,NJ,no,NaN,NaN,True,6.0,248920,NaN,NaN,NaN,28,28,3,0.0,10861,2244.0,0,43105,235,85841,129181,0.0,0.0,85443,0.0,0,33399,118842,10339,260393,78988,181405,0,49261,249,114328,163838,0,0,79349,0,41120,120469,43369,286080,61306,224774,no,no,no,no,no,yes,no,yes,yes,no,no,NaN,yes,no,NaN,NaN,no,no,yes,no,no,NaN,NaN,NaN,71494,NaN,NaN,510.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210502065_201712,2017v2.3,201802149349300720,MTA0MDA5Nzc5MzMwNzI5ODQ0OA

In [18]:
# identify governance columns of interest to me
list(enumerate(df_all_fields.columns))[66:89]

[(66, 'asset_net_endyr'),
 (67, 'operate_hospfacility'),
 (68, 'relationsamongemployees'),
 (69, 'delegate_management'),
 (70, 'material_diversion'),
 (71, 'memb_or_stockholder'),
 (72, 'memb_elect_board'),
 (73, 'decisions_outside_board'),
 (74, 'govern_body_minutes'),
 (75, 'committee_minutes'),
 (76, 'no_officer_address'),
 (77, 'local_chapt'),
 (78, 'policies_ref_chapt'),
 (79, '990_to_members'),
 (80, 'conflict_interest_policy'),
 (81, 'conflict_disclosure'),
 (82, 'enforce_conflict_policy'),
 (83, 'whistleblower_policy'),
 (84, 'doc_retention_policy'),
 (85, 'ceo_comp_review'),
 (86, 'officer_comp_review'),
 (87, 'in_joint_venture'),
 (88, 'joint_venture_policy')]

In [23]:
# add together columns selected by index and those manually selected
cols = list(df_all_fields.iloc[:, 68:89].columns) + ['ein',
  'tax_yr',
   'voting_memb_ct',
   'voting_indepmemb_ct',
   'employee_tot_ct',
   'volunteer_tot_ct']

In [57]:
# import only fields of interest to me
df = pd.read_csv('data_sets/Open990_Governance_Snack_Set_Public_2019-01-15.csv', usecols=cols)

In [25]:
df.head(5)

,ein,tax_yr,voting_memb_ct,voting_indepmemb_ct,employee_tot_ct,volunteer_tot_ct,relationsamongemployees,delegate_management,material_diversion,memb_or_stockholder,memb_elect_board,decisions_outside_board,govern_body_minutes,committee_minutes,no_officer_address,local_chapt,policies_ref_chapt,990_to_members,conflict_interest_policy,conflict_disclosure,enforce_conflict_policy,whistleblower_policy,doc_retention_policy,ceo_comp_review,officer_comp_review,in_joint_venture,joint_venture_policy
0,391546606,2017,9,9,8,25.0,no,no,no,no,no,no,yes,yes,no,no,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,NaN
1,640901077,2012,15,15,4,NaN,no,no,no,yes,yes,yes,yes,no,no,no,NaN,yes,yes,yes,yes,no,no,no,no,no,NaN
2,522113016,2015,15,15,16,0.0,no,no,no,no,no,no,yes,yes,no,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,no,NaN
3,454957549,2016,4,0,12,NaN,no,no,no,no,no,no,no,no,no,no,NaN,no,no,no,no,no,no,no,no,no,NaN
4,210502065,2017,28,28,3,0.0,no,no,no,no,yes,no,yes,yes,no,no,NaN,yes,no,NaN,NaN,no,no,yes,no,no,NaN

In [14]:
# examine distribution by years
df.tax_yr.value_counts()

2016    237448
2015    226022
2014    208950
2013    189195
2017    178537
2012    169291
2011    138173
2010     97353
2018      8239
Name: tax_yr, dtype: int64

In [58]:
# since I'm focusing on 2017 in the executive
# compensation dataset I will
# subset to only 2017 data in the governance data
df = df[df.tax_yr == 2017]

In [59]:
df.shape

(178537, 27)

In [34]:
# which fields are more than 60% null?
(df.isnull().mean() * 100)[(df.isnull().mean() * 100) > 60].index

Index(['policies_ref_chapt', 'joint_venture_policy'], dtype='object')

In [36]:
# drop columns that are mostly null
df.drop(['policies_ref_chapt', 'joint_venture_policy'], axis=1, inplace=True)

In [62]:
# examine data types of columns
# many of the binary colums are object
# I need to convert to bool
df.dtypes

ein                           int64
tax_yr                        int64
voting_memb_ct                int64
voting_indepmemb_ct           int64
employee_tot_ct               int64
volunteer_tot_ct            float64
relationsamongemployees      object
delegate_management          object
material_diversion           object
memb_or_stockholder          object
memb_elect_board             object
decisions_outside_board      object
govern_body_minutes          object
committee_minutes            object
no_officer_address           object
local_chapt                  object
policies_ref_chapt           object
990_to_members               object
conflict_interest_policy     object
conflict_disclosure          object
enforce_conflict_policy      object
whistleblower_policy         object
doc_retention_policy         object
ceo_comp_review              object
officer_comp_review          object
in_joint_venture             object
joint_venture_policy         object
dtype: object

In [69]:
df.select_dtypes(include=['object']).columns

Index(['relationsamongemployees', 'delegate_management', 'material_diversion',
       'memb_or_stockholder', 'memb_elect_board', 'decisions_outside_board',
       'govern_body_minutes', 'committee_minutes', 'no_officer_address',
       'local_chapt', 'policies_ref_chapt', '990_to_members',
       'conflict_interest_policy', 'conflict_disclosure',
       'enforce_conflict_policy', 'whistleblower_policy',
       'doc_retention_policy', 'ceo_comp_review', 'officer_comp_review',
       'in_joint_venture', 'joint_venture_policy'],
      dtype='object')

In [71]:
# convert object columns to boolean
for column in df.select_dtypes(include=['object']).columns:
    df[column] = df[column] == 'yes'

In [72]:
# verify results
df.dtypes

ein                           int64
tax_yr                        int64
voting_memb_ct                int64
voting_indepmemb_ct           int64
employee_tot_ct               int64
volunteer_tot_ct            float64
relationsamongemployees        bool
delegate_management            bool
material_diversion             bool
memb_or_stockholder            bool
memb_elect_board               bool
decisions_outside_board        bool
govern_body_minutes            bool
committee_minutes              bool
no_officer_address             bool
local_chapt                    bool
policies_ref_chapt             bool
990_to_members                 bool
conflict_interest_policy       bool
conflict_disclosure            bool
enforce_conflict_policy        bool
whistleblower_policy           bool
doc_retention_policy           bool
ceo_comp_review                bool
officer_comp_review            bool
in_joint_venture               bool
joint_venture_policy           bool
dtype: object

In [76]:
# examine for null values by percent
df.isnull().mean() * 100

ein                          0.000000
tax_yr                       0.000000
voting_memb_ct               0.000000
voting_indepmemb_ct          0.000000
employee_tot_ct              0.000000
volunteer_tot_ct            27.121549
relationsamongemployees      0.000000
delegate_management          0.000000
material_diversion           0.000000
memb_or_stockholder          0.000000
memb_elect_board             0.000000
decisions_outside_board      0.000000
govern_body_minutes          0.000000
committee_minutes            0.000000
no_officer_address           0.000000
local_chapt                  0.000000
policies_ref_chapt           0.000000
990_to_members               0.000000
conflict_interest_policy     0.000000
conflict_disclosure          0.000000
enforce_conflict_policy      0.000000
whistleblower_policy         0.000000
doc_retention_policy         0.000000
ceo_comp_review              0.000000
officer_comp_review          0.000000
in_joint_venture             0.000000
joint_venture_policy         0.000000
dtype: float64

In [77]:
# replace null volunteers with zero
df.volunteer_tot_ct.fillna(0, inplace=True)

In [79]:
df.head()

,ein,tax_yr,voting_memb_ct,voting_indepmemb_ct,employee_tot_ct,volunteer_tot_ct,relationsamongemployees,delegate_management,material_diversion,memb_or_stockholder,memb_elect_board,decisions_outside_board,govern_body_minutes,committee_minutes,no_officer_address,local_chapt,policies_ref_chapt,990_to_members,conflict_interest_policy,conflict_disclosure,enforce_conflict_policy,whistleblower_policy,doc_retention_policy,ceo_comp_review,officer_comp_review,in_joint_venture,joint_venture_policy
0,391546606,2017,9,9,8,25.0,False,False,False,False,False,False,True,True,False,False,False,True,True,True,True,True,True,True,False,False,False
4,210502065,2017,28,28,3,0.0,False,False,False,False,True,False,True,True,False,False,False,True,False,False,False,False,False,True,False,False,False
6,200096358,2017,4,4,9,0.0,False,False,False,False,False,False,True,True,False,False,False,True,True,True,True,False,True,True,False,False,False
28,721505381,2017,15,14,1,17.0,False,False,False,False,False,False,True,True,False,False,False,True,True,True,True,True,True,True,True,False,False
43,941186179,2017,19,18,220,19.0,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,True,False,True,True,False,False